2022-06-07 21:51:30,326 INFO    MainThread:12639 [wandb_setup.py:_flush():76] Loading settings from /home/shuffle/.config/wandb/settings
2022-06-07 21:51:30,326 INFO    MainThread:12639 [wandb_setup.py:_flush():76] Loading settings from /home/shuffle/DL-IAD-HSE/DeepLearning/Метод обратного распространения ошибки. Свёртки и свёрточные слои/Seminar/wandb/settings
2022-06-07 21:51:30,326 INFO    MainThread:12639 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-07 21:51:30,326 INFO    MainThread:12639 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-06-07 21:51:30,327 INFO    MainThread:12639 [wandb_init.py:_log_setup():428] Logging user logs to /home/shuffle/DL-IAD-HSE/DeepLearning/Метод обратного распространения ошибки. Свёртки и свёрточные слои/Seminar/wandb/run-20220607_215130-3nl9bgq5/logs/debug.log
2022-06-07 21:51:30,327 INFO    MainThread:12639 [wandb_init.py:_log_setup():429] Logging internal logs to /home/shuffle/DL-IAD-HSE/DeepLearning/Метод обратного распространения ошибки. Свёртки и свёрточные слои/Seminar/wandb/run-20220607_215130-3nl9bgq5/logs/debug-internal.log
2022-06-07 21:51:30,352 INFO    MainThread:12639 [wandb_init.py:init():462] calling init triggers
2022-06-07 21:51:30,352 INFO    MainThread:12639 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'architecture': 'CNN', 'dataset_id': 'MNIST'}
2022-06-07 21:51:30,352 INFO    MainThread:12639 [wandb_init.py:init():481] re-initializing run, found existing run on stack: 3u2bxm2e
2022-06-07 21:51:30,355 INFO    MainThread:12639 [wandb_run.py:_finish():1685] finishing run shuffle-krakens/Sem-02/3u2bxm2e
2022-06-07 21:51:30,356 INFO    MainThread:12639 [jupyter.py:save_history():435] not saving jupyter history
2022-06-07 21:51:30,356 INFO    MainThread:12639 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-06-07 21:51:30,356 INFO    MainThread:12639 [wandb_init.py:_jupyter_teardown():360] cleaning up jupyter logic
2022-06-07 21:51:30,356 INFO    MainThread:12639 [wandb_run.py:_atexit_cleanup():1867] got exitcode: 0
2022-06-07 21:51:30,360 INFO    MainThread:12639 [wandb_run.py:_restore():1839] restore
2022-06-07 21:51:30,581 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 1026
}

2022-06-07 21:51:30,886 INFO    MainThread:12639 [wandb_init.py:init():515] starting backend
2022-06-07 21:51:30,887 INFO    MainThread:12639 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-06-07 21:51:30,890 INFO    MainThread:12639 [backend.py:ensure_launched():217] starting backend process...
2022-06-07 21:51:30,904 INFO    MainThread:12639 [backend.py:ensure_launched():222] started backend process with pid: 15089
2022-06-07 21:51:30,906 INFO    MainThread:12639 [wandb_init.py:init():525] backend started and connected
2022-06-07 21:51:30,939 INFO    MainThread:12639 [wandb_run.py:_label_probe_notebook():1089] probe notebook
2022-06-07 21:51:30,940 INFO    MainThread:12639 [wandb_run.py:_label_probe_notebook():1099] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-06-07 21:51:30,940 INFO    MainThread:12639 [wandb_init.py:init():596] updated telemetry
2022-06-07 21:51:30,993 INFO    MainThread:12639 [wandb_init.py:init():627] communicating run to backend with 30 second timeout
2022-06-07 21:51:32,481 WARNING MainThread:12639 [wandb_init.py:init():1020] interrupted
Traceback (most recent call last):
  File "/home/shuffle/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 999, in init
    run = wi.init()
  File "/home/shuffle/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 630, in init
    run_result = backend.interface.communicate_run(
  File "/home/shuffle/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 223, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/shuffle/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 324, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/shuffle/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/shuffle/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/shuffle/anaconda3/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/shuffle/anaconda3/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2022-06-07 21:51:41,569 INFO    MainThread:12639 [wandb_setup.py:_flush():76] Loading settings from /home/shuffle/.config/wandb/settings
2022-06-07 21:51:41,569 INFO    MainThread:12639 [wandb_setup.py:_flush():76] Loading settings from /home/shuffle/DL-IAD-HSE/DeepLearning/Метод обратного распространения ошибки. Свёртки и свёрточные слои/Seminar/wandb/settings
2022-06-07 21:51:41,570 INFO    MainThread:12639 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-07 21:51:41,570 INFO    MainThread:12639 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-06-07 21:51:41,570 INFO    MainThread:12639 [wandb_init.py:_log_setup():428] Logging user logs to /home/shuffle/DL-IAD-HSE/DeepLearning/Метод обратного распространения ошибки. Свёртки и свёрточные слои/Seminar/wandb/run-20220607_215141-3cg0fbks/logs/debug.log
2022-06-07 21:51:41,570 INFO    MainThread:12639 [wandb_init.py:_log_setup():429] Logging internal logs to /home/shuffle/DL-IAD-HSE/DeepLearning/Метод обратного распространения ошибки. Свёртки и свёрточные слои/Seminar/wandb/run-20220607_215141-3cg0fbks/logs/debug-internal.log
2022-06-07 21:51:41,571 INFO    MainThread:12639 [wandb_init.py:_jupyter_setup():378] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f85c6b63a00>
2022-06-07 21:51:41,572 INFO    MainThread:12639 [wandb_init.py:init():462] calling init triggers
2022-06-07 21:51:41,572 INFO    MainThread:12639 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'architecture': 'CNN', 'dataset_id': 'MNIST'}
2022-06-07 21:51:41,573 INFO    MainThread:12639 [wandb_init.py:init():515] starting backend
2022-06-07 21:51:41,573 INFO    MainThread:12639 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-06-07 21:51:41,577 INFO    MainThread:12639 [backend.py:ensure_launched():217] starting backend process...
2022-06-07 21:51:41,586 INFO    MainThread:12639 [backend.py:ensure_launched():222] started backend process with pid: 15129
2022-06-07 21:51:41,588 INFO    MainThread:12639 [wandb_init.py:init():525] backend started and connected
2022-06-07 21:51:41,613 INFO    MainThread:12639 [wandb_run.py:_label_probe_notebook():1089] probe notebook
2022-06-07 21:51:41,613 INFO    MainThread:12639 [wandb_run.py:_label_probe_notebook():1099] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-06-07 21:51:41,614 INFO    MainThread:12639 [wandb_init.py:init():596] updated telemetry
2022-06-07 21:51:41,653 INFO    MainThread:12639 [wandb_init.py:init():627] communicating run to backend with 30 second timeout
2022-06-07 21:51:43,710 INFO    MainThread:12639 [wandb_run.py:_on_init():1924] communicating current version
2022-06-07 21:51:43,867 INFO    MainThread:12639 [wandb_run.py:_on_init():1928] got version response 
2022-06-07 21:51:43,867 INFO    MainThread:12639 [wandb_init.py:init():662] starting run threads in backend
2022-06-07 21:51:48,885 INFO    MainThread:12639 [wandb_run.py:_console_start():1898] atexit reg
2022-06-07 21:51:48,886 INFO    MainThread:12639 [wandb_run.py:_redirect():1771] redirect: SettingsConsole.WRAP
2022-06-07 21:51:48,886 INFO    MainThread:12639 [wandb_run.py:_redirect():1808] Wrapping output streams.
2022-06-07 21:51:48,889 INFO    MainThread:12639 [wandb_run.py:_redirect():1832] Redirects installed.
2022-06-07 21:51:48,889 INFO    MainThread:12639 [wandb_init.py:init():688] run started, returning control to user process
2022-06-07 21:51:48,890 INFO    MainThread:12639 [wandb_watch.py:watch():47] Watching
2022-06-07 22:10:25,005 INFO    MainThread:12639 [wandb_init.py:_pause_backend():341] pausing backend
2022-06-07 22:10:25,005 INFO    MainThread:12639 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-06-07 22:10:27,864 INFO    MainThread:12639 [wandb_init.py:_resume_backend():350] resuming backend
2022-06-07 22:10:27,885 INFO    MainThread:12639 [wandb_init.py:_pause_backend():341] pausing backend
2022-06-07 22:10:27,886 INFO    MainThread:12639 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-06-07 22:11:00,884 INFO    MainThread:12639 [wandb_init.py:_resume_backend():350] resuming backend
2022-06-07 22:11:01,121 INFO    MainThread:12639 [wandb_setup.py:_flush():76] Loading settings from /home/shuffle/.config/wandb/settings
2022-06-07 22:11:01,121 INFO    MainThread:12639 [wandb_setup.py:_flush():76] Loading settings from /home/shuffle/DL-IAD-HSE/DeepLearning/Метод обратного распространения ошибки. Свёртки и свёрточные слои/Seminar/wandb/settings
2022-06-07 22:11:01,121 INFO    MainThread:12639 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-07 22:11:01,122 INFO    MainThread:12639 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-06-07 22:11:01,122 INFO    MainThread:12639 [wandb_init.py:_log_setup():428] Logging user logs to /home/shuffle/DL-IAD-HSE/DeepLearning/Метод обратного распространения ошибки. Свёртки и свёрточные слои/Seminar/wandb/run-20220607_221101-3q6zfutn/logs/debug.log
2022-06-07 22:11:01,122 INFO    MainThread:12639 [wandb_init.py:_log_setup():429] Logging internal logs to /home/shuffle/DL-IAD-HSE/DeepLearning/Метод обратного распространения ошибки. Свёртки и свёрточные слои/Seminar/wandb/run-20220607_221101-3q6zfutn/logs/debug-internal.log
2022-06-07 22:11:01,122 INFO    MainThread:12639 [wandb_init.py:init():462] calling init triggers
2022-06-07 22:11:01,122 INFO    MainThread:12639 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'architecture': 'CNN2', 'dataset_id': 'MNIST'}
2022-06-07 22:11:01,123 INFO    MainThread:12639 [wandb_init.py:init():481] re-initializing run, found existing run on stack: 3cg0fbks
2022-06-07 22:11:01,125 INFO    MainThread:12639 [wandb_run.py:_finish():1685] finishing run shuffle-krakens/Sem-02/3cg0fbks
2022-06-07 22:11:01,125 INFO    MainThread:12639 [jupyter.py:save_history():435] not saving jupyter history
2022-06-07 22:11:01,126 INFO    MainThread:12639 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-06-07 22:11:01,126 INFO    MainThread:12639 [wandb_init.py:_jupyter_teardown():360] cleaning up jupyter logic
2022-06-07 22:11:01,126 INFO    MainThread:12639 [wandb_run.py:_atexit_cleanup():1867] got exitcode: 0
2022-06-07 22:11:01,127 INFO    MainThread:12639 [wandb_run.py:_restore():1839] restore
2022-06-07 22:11:02,206 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 1026
}

2022-06-07 22:11:02,489 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 1026
}

2022-06-07 22:11:02,745 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 114008
}

2022-06-07 22:11:02,848 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 119985
}

2022-06-07 22:11:02,951 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 119985
}

2022-06-07 22:11:03,055 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 119985
}

2022-06-07 22:11:03,157 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 119985
  total_bytes: 119985
}

2022-06-07 22:11:03,260 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 119985
  total_bytes: 119985
}

2022-06-07 22:11:03,363 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 119985
  total_bytes: 119985
}

2022-06-07 22:11:03,465 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 119985
  total_bytes: 119985
}

2022-06-07 22:11:03,567 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 119985
  total_bytes: 119985
}

2022-06-07 22:11:03,669 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 119985
  total_bytes: 119985
}

2022-06-07 22:11:03,771 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 119985
  total_bytes: 119985
}

2022-06-07 22:11:03,873 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 119985
  total_bytes: 119985
}

2022-06-07 22:11:04,828 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 119985
  total_bytes: 119985
}

2022-06-07 22:11:05,682 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 119985
  total_bytes: 119985
}
local_info {
}

2022-06-07 22:11:06,980 INFO    MainThread:12639 [wandb_run.py:_footer_history_summary_info():3104] rendering history
2022-06-07 22:11:06,981 INFO    MainThread:12639 [wandb_run.py:_footer_history_summary_info():3136] rendering summary
2022-06-07 22:11:06,987 INFO    MainThread:12639 [wandb_run.py:_footer_sync_info():3060] logging synced files
2022-06-07 22:11:06,996 INFO    MainThread:12639 [wandb_init.py:init():515] starting backend
2022-06-07 22:11:06,997 INFO    MainThread:12639 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-06-07 22:11:07,000 INFO    MainThread:12639 [backend.py:ensure_launched():217] starting backend process...
2022-06-07 22:11:07,016 INFO    MainThread:12639 [backend.py:ensure_launched():222] started backend process with pid: 18243
2022-06-07 22:11:07,020 INFO    MainThread:12639 [wandb_init.py:init():525] backend started and connected
2022-06-07 22:11:07,071 INFO    MainThread:12639 [wandb_run.py:_label_probe_notebook():1089] probe notebook
2022-06-07 22:11:07,072 INFO    MainThread:12639 [wandb_run.py:_label_probe_notebook():1099] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-06-07 22:11:07,073 INFO    MainThread:12639 [wandb_init.py:init():596] updated telemetry
2022-06-07 22:11:07,118 INFO    MainThread:12639 [wandb_init.py:init():627] communicating run to backend with 30 second timeout
2022-06-07 22:11:09,095 INFO    MainThread:12639 [wandb_run.py:_on_init():1924] communicating current version
2022-06-07 22:11:09,236 INFO    MainThread:12639 [wandb_run.py:_on_init():1928] got version response 
2022-06-07 22:11:09,236 INFO    MainThread:12639 [wandb_init.py:init():662] starting run threads in backend
2022-06-07 22:11:14,253 INFO    MainThread:12639 [wandb_run.py:_console_start():1898] atexit reg
2022-06-07 22:11:14,254 INFO    MainThread:12639 [wandb_run.py:_redirect():1771] redirect: SettingsConsole.WRAP
2022-06-07 22:11:14,255 INFO    MainThread:12639 [wandb_run.py:_redirect():1808] Wrapping output streams.
2022-06-07 22:11:14,256 INFO    MainThread:12639 [wandb_run.py:_redirect():1832] Redirects installed.
2022-06-07 22:11:14,256 INFO    MainThread:12639 [wandb_init.py:init():688] run started, returning control to user process
2022-06-07 22:11:14,257 INFO    MainThread:12639 [wandb_watch.py:watch():47] Watching
2022-06-07 23:38:26,038 INFO    MainThread:12639 [wandb_run.py:_atexit_cleanup():1867] got exitcode: 0
2022-06-07 23:38:26,040 INFO    MainThread:12639 [wandb_run.py:_restore():1839] restore
2022-06-07 23:38:26,604 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 1026
}

2022-06-07 23:38:27,071 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 1026
}

2022-06-07 23:38:27,209 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 76894
}

2022-06-07 23:38:27,312 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 82871
}

2022-06-07 23:38:27,415 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 82871
}

2022-06-07 23:38:27,517 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 82871
}

2022-06-07 23:38:27,619 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 82871
}

2022-06-07 23:38:27,721 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 67814
  total_bytes: 82871
}

2022-06-07 23:38:27,824 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 82871
  total_bytes: 82871
}

2022-06-07 23:38:27,926 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 82871
  total_bytes: 82871
}

2022-06-07 23:38:28,029 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 82871
  total_bytes: 82871
}

2022-06-07 23:38:28,131 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 82871
  total_bytes: 82871
}

2022-06-07 23:38:28,232 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 82871
  total_bytes: 82871
}

2022-06-07 23:38:28,334 INFO    MainThread:12639 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 82871
  total_bytes: 82871
}

